---
title: About me
---

I'm a [Senior Statistician](https://www.rand.org/about/people/c/crawford_forrest.html) at the [RAND](https://rand.org) Meselson Center working on biosecurity and emerging technology.  I'm also the Senior Scientist at [Whitespace](https://inthewhitespace.com/), a geospatial intelligence company. 

I'm on leave from [my other job](https://ysph.yale.edu/profile/forrest_crawford/) as a full-time professor at [Yale University](http://www.yale.edu) in the Departments of [Biostatistics](http://publichealth.yale.edu/biostat), [Statistics & Data Science](https://statistics.yale.edu), [Operations](http://som.yale.edu/programs/doctoral/overview/operations), and [Ecology & Evolutionary Biology](http://eeb.yale.edu).  I have taught courses on stochastic processes, computational statistics, modeling, and causal inference. At Yale I worked on lots of things, including the COVID-19 pandemic response, the opioid overdose crisis, HIV outbreaks, and methods for studying hidden and hard-to-reach populations. In 2016 I received the [NIH Director's New Innovator Award (DP2)](https://commonfund.nih.gov/newinnovator). 

My methodological/quantitative interests are broad. I'm interested in AI/ML, applied math, stochastic processes, modeling, causal inference, networks/graphs, computation, optimization, and algorithms.  

I've worked in a variety of applied fields, including public health, security, human rights, biomedical science, epidemiology, neuroscience, evolutionary biology, bioengineering, radiology, and sociology. 

Please [get in touch](contact) if you'd like to talk. Or, you can [leave me anonymous feedback](https://www.admonymous.co/forrestcrawford). 


